### ISSUE TITLE
make MongoDB not required?

### ISSUE THREAD

**Issue by techieshark** [techieshark/slack-pair#15]
To make it so users can get up and running quickly with an in-memory store, we might want to not require MongoDB.

This might also help with possibly running on Redis or something later too.

**Comment by dferrantelli** [comment]
I agree, if we abstract the storage and retrieval, we can have it default to in mem, then use mongo (or redis?) if the connection url is set.

**Comment by techieshark** [comment]
@dferrantelli yeah, sounds good. My next step was going to be make it so it defaults to memory if db url isn't set. I'll try to think about the abstraction while doing that.
