### ISSUE TITLE
Is in memory data store the right way to go?

### ISSUE THREAD

**Issue by jeremiak** [techieshark/slack-pair#2]
I know we're lazy, and I appreciate that, but perhaps having the state stored in-memory on Heroku ain't the best idea

**Comment by dferrantelli** [comment]
I can't believe i'm saying this, but redis would to the trick. might try to put together a PR later if I get it working.

**Comment by techieshark** [comment]
Hey @dferrantelli, I'd be excited to take a look at this if you worked on it.

**Comment by techieshark** [comment]
I wanted to play around with MongoDB so I added support for that (https://github.com/techieshark/slack-pair/commit/598e4ff45bbe6c7b7e931914aede5cb056249d66) as one way to persist information. 

@dferrantelli Would that work for you? Otherwise if you or others want this to work with redis I'd be happy to help support that as an option.

**Comment by dferrantelli** [comment]
Hey, sorry with XMas so close things have gotten a little hectic. i would have preferred redis mostly because it is lighter weight. Maybe we can have it use either by setting an env var?

**Comment by techieshark** [comment]
@dferrantelli Check out the commit that closed #15 . We can now run in memory or with MongoDB if people have that and set `DB_PROVIDER=mongo` in their environment. Merry XMas! 

Did you want to take a stab at Redis support? You could do that by changing [this line](https://github.com/techieshark/slack-pair/blob/f149d0c8cb1b4983d5a2728d8f77acad1933911a/lib/pair_db.js#L30), and adding a `lib/pair_db_redis.js` and `lib/pair_list_redis.js` (see the mongo version of those files for an example).

**Comment by techieshark** [comment]
Documented Mongo settings in README: https://github.com/techieshark/slack-pair/commit/5ed72df649099965e7af5afd7964305f6b394c27

Closing this issue now. @dferrantelli feel free to open a new one 'support Redis' if you'd like!
